global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: monitoring
    metrics_path: /metrics
    static_configs:
      - targets:
          - "my-app-container:8000"

  # - job_name: logstash
  #   metrics_path: /metrics
  #   static_configs:
  #     - targets:
  #         - "my_logstash_container:9600"
